module.exports = {
  id: '',
  fellow: {
    id: '',
    email: '',
    first_name: '',
    last_name: '',
    location: '',
    level: '',
    name: '',
    picture: '',
  },
  fellow_id: '',
  status: '',
  type: '',
  client_name: '',
  placement_mode: '',
  engagement_id: '',
  start_date: '',
  end_date: '',
  created_at: '',
  updated_at: '',
  updated_by: '',
  salesforce_id: '',
  engagement_role_id: '',
  engagement_role: null,
  next_available_date: '',
  sync_status: '',
  client_id: '',
};
