version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment: 
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_USER=${DB_USER_NAME}"
      - "POSTGRES_DB=${DB_DEV_NAME}"
  backend:
    image: esa-backend:latest
    env_file: .env
    build: 
      context: .
    ports:
      - "6050:${PORT}"
      - "9229:9229"
    volumes:
      - "${PWD}:/usr/src/app/"
      - /usr/src/app/node_modules
    environment: 
      - "DB_HOST=database"
      - "REDIS_HOST=redis"
    depends_on:
      - redis
      - database
    command: "npm run start:dev"